version: '3.8'

services:
  app:
    build: .
    container_name: restaurant_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=restaurant_app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant_app
    volumes:
      - db_data:/var/lib/mysql
      - ./database/restaurant_app.sql:/docker-entrypoint-initdb.d/restaurant_app.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
